export const DIVISIONS_NUMBER = 24
export const ITEM_HEIGHT = 50
export const COLUMN_HEIGHT = ITEM_HEIGHT * DIVISIONS_NUMBER
export const MINUTES_IN_DAY = 60 * 24
export const MINUTES_IN_DIVISION = MINUTES_IN_DAY / DIVISIONS_NUMBER
